export type ThemeId =
  | "minimal"
  | "linear"
  | "vercel"
  | "neon"
  | "warp"
  | "mono"
  | "terminal"
  | "trading"
  | "raycast";

export interface ThemeColors {
  chartPalette: string[];
  chartDim: string;
  chartAxis: string;
  chartGrid: string;
  tokenInput: string;
  tokenOutput: string;
  tokenCacheCreation: string;
  tokenCacheRead: string;
  tokenCost: string;
  accent: string;
  accentFg: string;
  textPrimary: string;
}

export interface Theme {
  id: ThemeId;
  label: string;
  description: string;
  cssVars: Record<string, string>;
  colors: ThemeColors;
}

const MINIMAL: Theme = {
  id: "minimal",
  label: "Minimal",
  description: "Neutral grays, single accent",
  cssVars: {
    "--bg-app": "#fafafa",
    "--bg-panel": "#ffffff",
    "--bg-panel-muted": "#f4f4f5",
    "--bg-input": "#f4f4f5",
    "--border": "#e4e4e7",
    "--border-strong": "#d4d4d8",
    "--text-primary": "#09090b",
    "--text-secondary": "#27272a",
    "--text-muted": "#71717a",
    "--text-subtle": "#a1a1aa",
    "--accent": "#000000",
    "--accent-fg": "#ffffff",
    "--shadow-card": "none",
    "--radius-card": "0.5rem",
    "--font-body":
      'ui-sans-serif, Inter, system-ui, -apple-system, sans-serif',
    "--font-mono":
      'ui-monospace, "SF Mono", Menlo, monospace',
    "--badge-bg": "#f4f4f5",
    "--badge-fg": "#3f3f46",
    "--header-eyebrow": "#71717a",
    "--code-bg": "#fafafa",
    "--code-fg": "#09090b",
    "--code-border": "#d4d4d8",
    "--bubble-user-bg": "#f4f4f5",
    "--bubble-user-fg": "#09090b",
    "--bubble-assistant-bg": "#ffffff",
    "--bubble-assistant-fg": "#09090b",
    "--thinking-bg": "#fafafa",
    "--thinking-border": "#e4e4e7",
    "--overlay-bg": "rgba(9, 9, 11, 0.5)",
  },
  colors: {
    chartPalette: ["#18181b", "#3f3f46", "#71717a", "#2563eb", "#a1a1aa", "#d4d4d8", "#52525b", "#27272a"],
    chartDim: "#e4e4e7",
    chartAxis: "#a1a1aa",
    chartGrid: "#e4e4e7",
    tokenInput: "#d4d4d8",
    tokenOutput: "#18181b",
    tokenCacheCreation: "#a1a1aa",
    tokenCacheRead: "#e4e4e7",
    tokenCost: "#2563eb",
    accent: "#000000",
    accentFg: "#ffffff",
    textPrimary: "#09090b",
  },
};

const LINEAR: Theme = {
  id: "linear",
  label: "Linear",
  description: "Indigo accent, refined product feel",
  cssVars: {
    "--bg-app": "#f7f8fa",
    "--bg-panel": "#ffffff",
    "--bg-panel-muted": "#f1f2f5",
    "--bg-input": "#f1f2f5",
    "--border": "#e6e8ee",
    "--border-strong": "#d0d3dc",
    "--text-primary": "#1a1c24",
    "--text-secondary": "#3e4049",
    "--text-muted": "#6e7079",
    "--text-subtle": "#9ca0ac",
    "--accent": "#5e6ad2",
    "--accent-fg": "#ffffff",
    "--shadow-card": "0 1px 2px rgba(15, 18, 30, 0.04), 0 1px 3px rgba(15, 18, 30, 0.03)",
    "--radius-card": "0.5rem",
    "--font-body":
      '"Inter Variable", "Inter", ui-sans-serif, system-ui, -apple-system, sans-serif',
    "--font-mono":
      '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
    "--badge-bg": "#ecedf3",
    "--badge-fg": "#3e4049",
    "--header-eyebrow": "#5e6ad2",
    "--code-bg": "#f5f6f9",
    "--code-fg": "#1a1c24",
    "--code-border": "#e0e2ea",
    "--bubble-user-bg": "#eceffd",
    "--bubble-user-fg": "#1a1c24",
    "--bubble-assistant-bg": "#ffffff",
    "--bubble-assistant-fg": "#1a1c24",
    "--thinking-bg": "#f5f6f9",
    "--thinking-border": "#e0e2ea",
    "--overlay-bg": "rgba(20, 22, 30, 0.48)",
  },
  colors: {
    chartPalette: ["#5e6ad2", "#26a69a", "#ef6461", "#f2c94c", "#9b59b6", "#4a90e2", "#7cb342", "#ec4899"],
    chartDim: "#e6e8ee",
    chartAxis: "#9ca0ac",
    chartGrid: "#eef0f4",
    tokenInput: "#a4aff1",
    tokenOutput: "#5e6ad2",
    tokenCacheCreation: "#79c6c0",
    tokenCacheRead: "#c7e3df",
    tokenCost: "#ef6461",
    accent: "#5e6ad2",
    accentFg: "#ffffff",
    textPrimary: "#1a1c24",
  },
};

const VERCEL: Theme = {
  id: "vercel",
  label: "Vercel",
  description: "Pure black & white, geometric",
  cssVars: {
    "--bg-app": "#000000",
    "--bg-panel": "#0a0a0a",
    "--bg-panel-muted": "#111111",
    "--bg-input": "#111111",
    "--border": "#262626",
    "--border-strong": "#404040",
    "--text-primary": "#ededed",
    "--text-secondary": "#a3a3a3",
    "--text-muted": "#737373",
    "--text-subtle": "#525252",
    "--accent": "#ffffff",
    "--accent-fg": "#000000",
    "--shadow-card": "none",
    "--radius-card": "0.5rem",
    "--font-body":
      '"Geist", "Geist Variable", "Inter", ui-sans-serif, system-ui, sans-serif',
    "--font-mono":
      '"Geist Mono", "JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
    "--badge-bg": "#171717",
    "--badge-fg": "#ededed",
    "--header-eyebrow": "#a3a3a3",
    "--code-bg": "#0a0a0a",
    "--code-fg": "#ededed",
    "--code-border": "#262626",
    "--bubble-user-bg": "#171717",
    "--bubble-user-fg": "#ededed",
    "--bubble-assistant-bg": "#0a0a0a",
    "--bubble-assistant-fg": "#ededed",
    "--thinking-bg": "#0a0a0a",
    "--thinking-border": "#262626",
    "--overlay-bg": "rgba(0, 0, 0, 0.8)",
  },
  colors: {
    chartPalette: ["#ffffff", "#a3a3a3", "#737373", "#0070f3", "#7928ca", "#f81ce5", "#50e3c2", "#f5a623"],
    chartDim: "#262626",
    chartAxis: "#525252",
    chartGrid: "#171717",
    tokenInput: "#a3a3a3",
    tokenOutput: "#ededed",
    tokenCacheCreation: "#0070f3",
    tokenCacheRead: "#50e3c2",
    tokenCost: "#f81ce5",
    accent: "#ffffff",
    accentFg: "#000000",
    textPrimary: "#ededed",
  },
};

const NEON: Theme = {
  id: "neon",
  label: "Neon",
  description: "Deep navy, electric green accent",
  cssVars: {
    "--bg-app": "#0a0e1a",
    "--bg-panel": "#10152b",
    "--bg-panel-muted": "#151b33",
    "--bg-input": "#151b33",
    "--border": "#1e2544",
    "--border-strong": "#2d355a",
    "--text-primary": "#e8ecff",
    "--text-secondary": "#b4bce6",
    "--text-muted": "#7a83ad",
    "--text-subtle": "#4a5177",
    "--accent": "#00e599",
    "--accent-fg": "#0a0e1a",
    "--shadow-card": "0 0 0 1px rgba(0, 229, 153, 0.08), 0 8px 24px rgba(0, 229, 153, 0.05)",
    "--radius-card": "0.75rem",
    "--font-body":
      '"Inter", ui-sans-serif, system-ui, sans-serif',
    "--font-mono":
      '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
    "--badge-bg": "#1a2040",
    "--badge-fg": "#7ceec0",
    "--header-eyebrow": "#00e599",
    "--code-bg": "#070a14",
    "--code-fg": "#7ceec0",
    "--code-border": "#1e2544",
    "--bubble-user-bg": "#1a2040",
    "--bubble-user-fg": "#e8ecff",
    "--bubble-assistant-bg": "#10152b",
    "--bubble-assistant-fg": "#e8ecff",
    "--thinking-bg": "#0f1a2b",
    "--thinking-border": "#1e2544",
    "--overlay-bg": "rgba(5, 7, 15, 0.72)",
  },
  colors: {
    chartPalette: ["#00e599", "#6366f1", "#f472b6", "#38bdf8", "#facc15", "#fb7185", "#a78bfa", "#34d399"],
    chartDim: "#1e2544",
    chartAxis: "#4a5177",
    chartGrid: "#1a2040",
    tokenInput: "#6366f1",
    tokenOutput: "#00e599",
    tokenCacheCreation: "#38bdf8",
    tokenCacheRead: "#7ceec0",
    tokenCost: "#f472b6",
    accent: "#00e599",
    accentFg: "#0a0e1a",
    textPrimary: "#e8ecff",
  },
};

const WARP: Theme = {
  id: "warp",
  label: "Warp",
  description: "Modern terminal, purple-tinted dark",
  cssVars: {
    "--bg-app": "#1c1b22",
    "--bg-panel": "#232229",
    "--bg-panel-muted": "#2a2932",
    "--bg-input": "#2a2932",
    "--border": "#34333d",
    "--border-strong": "#4a4955",
    "--text-primary": "#e8e6f0",
    "--text-secondary": "#bdbac9",
    "--text-muted": "#8a8795",
    "--text-subtle": "#5e5c6a",
    "--accent": "#9d7cff",
    "--accent-fg": "#1c1b22",
    "--shadow-card": "0 4px 12px rgba(0, 0, 0, 0.25)",
    "--radius-card": "0.625rem",
    "--font-body":
      '"Hack", "JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
    "--font-mono":
      '"Hack", "JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
    "--badge-bg": "#332e4d",
    "--badge-fg": "#c9b8ff",
    "--header-eyebrow": "#9d7cff",
    "--code-bg": "#16151b",
    "--code-fg": "#c9b8ff",
    "--code-border": "#34333d",
    "--bubble-user-bg": "#332e4d",
    "--bubble-user-fg": "#e8e6f0",
    "--bubble-assistant-bg": "#232229",
    "--bubble-assistant-fg": "#e8e6f0",
    "--thinking-bg": "#272334",
    "--thinking-border": "#34333d",
    "--overlay-bg": "rgba(10, 9, 14, 0.72)",
  },
  colors: {
    chartPalette: ["#9d7cff", "#5eead4", "#f472b6", "#facc15", "#fb923c", "#60a5fa", "#a3e635", "#f87171"],
    chartDim: "#34333d",
    chartAxis: "#5e5c6a",
    chartGrid: "#2a2932",
    tokenInput: "#60a5fa",
    tokenOutput: "#9d7cff",
    tokenCacheCreation: "#5eead4",
    tokenCacheRead: "#a3e635",
    tokenCost: "#f472b6",
    accent: "#9d7cff",
    accentFg: "#1c1b22",
    textPrimary: "#e8e6f0",
  },
};

const MONO: Theme = {
  id: "mono",
  label: "Mono",
  description: "Editorial magazine — serif, cream, red accent",
  cssVars: {
    "--bg-app": "#f5f1e8",
    "--bg-panel": "#fdfbf5",
    "--bg-panel-muted": "#ebe6d8",
    "--bg-input": "#ebe6d8",
    "--border": "#1a1a1a",
    "--border-strong": "#1a1a1a",
    "--text-primary": "#0a0a0a",
    "--text-secondary": "#2a2a2a",
    "--text-muted": "#5a5a5a",
    "--text-subtle": "#8a8a8a",
    "--accent": "#c41e3a",
    "--accent-fg": "#fdfbf5",
    "--shadow-card": "none",
    "--radius-card": "0",
    "--font-body":
      '"Times New Roman", "Playfair Display", Georgia, "Iowan Old Style", serif',
    "--font-mono":
      '"Courier Prime", "Courier New", ui-monospace, monospace',
    "--badge-bg": "#0a0a0a",
    "--badge-fg": "#fdfbf5",
    "--header-eyebrow": "#c41e3a",
    "--code-bg": "#ebe6d8",
    "--code-fg": "#0a0a0a",
    "--code-border": "#0a0a0a",
    "--bubble-user-bg": "#0a0a0a",
    "--bubble-user-fg": "#fdfbf5",
    "--bubble-assistant-bg": "#fdfbf5",
    "--bubble-assistant-fg": "#0a0a0a",
    "--thinking-bg": "#ebe6d8",
    "--thinking-border": "#0a0a0a",
    "--overlay-bg": "rgba(10, 10, 10, 0.55)",
  },
  colors: {
    chartPalette: ["#0a0a0a", "#c41e3a", "#5a5a5a", "#8a8a8a", "#2a2a2a", "#c0a060", "#406080", "#a0502a"],
    chartDim: "#d4cfc0",
    chartAxis: "#5a5a5a",
    chartGrid: "#d4cfc0",
    tokenInput: "#5a5a5a",
    tokenOutput: "#0a0a0a",
    tokenCacheCreation: "#8a8a8a",
    tokenCacheRead: "#c0a060",
    tokenCost: "#c41e3a",
    accent: "#c41e3a",
    accentFg: "#fdfbf5",
    textPrimary: "#0a0a0a",
  },
};

const TERMINAL: Theme = {
  id: "terminal",
  label: "Terminal",
  description: "Black + neon green, monospace",
  cssVars: {
    "--bg-app": "#000000",
    "--bg-panel": "#0a0a0a",
    "--bg-panel-muted": "#111111",
    "--bg-input": "#0a0a0a",
    "--border": "#1f2937",
    "--border-strong": "#374151",
    "--text-primary": "#4ade80",
    "--text-secondary": "#86efac",
    "--text-muted": "#4b5563",
    "--text-subtle": "#374151",
    "--accent": "#22c55e",
    "--accent-fg": "#000000",
    "--shadow-card": "0 0 0 1px rgba(34, 197, 94, 0.15)",
    "--radius-card": "0.25rem",
    "--font-body":
      '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace',
    "--font-mono":
      '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace',
    "--badge-bg": "#052e16",
    "--badge-fg": "#4ade80",
    "--header-eyebrow": "#22c55e",
    "--code-bg": "#020617",
    "--code-fg": "#86efac",
    "--code-border": "#166534",
    "--bubble-user-bg": "#052e16",
    "--bubble-user-fg": "#86efac",
    "--bubble-assistant-bg": "#0a0a0a",
    "--bubble-assistant-fg": "#4ade80",
    "--thinking-bg": "#052e16",
    "--thinking-border": "#166534",
    "--overlay-bg": "rgba(0, 0, 0, 0.7)",
  },
  colors: {
    chartPalette: ["#22c55e", "#4ade80", "#86efac", "#16a34a", "#15803d", "#166534", "#14532d", "#052e16"],
    chartDim: "#1f2937",
    chartAxis: "#4b5563",
    chartGrid: "#1f2937",
    tokenInput: "#4ade80",
    tokenOutput: "#22c55e",
    tokenCacheCreation: "#16a34a",
    tokenCacheRead: "#15803d",
    tokenCost: "#86efac",
    accent: "#22c55e",
    accentFg: "#000000",
    textPrimary: "#4ade80",
  },
};

const TRADING: Theme = {
  id: "trading",
  label: "Trading",
  description: "Bloomberg — dark + amber, dense",
  cssVars: {
    "--bg-app": "#0b0e14",
    "--bg-panel": "#11151c",
    "--bg-panel-muted": "#161b24",
    "--bg-input": "#161b24",
    "--border": "#1f2937",
    "--border-strong": "#374151",
    "--text-primary": "#f59e0b",
    "--text-secondary": "#fbbf24",
    "--text-muted": "#9ca3af",
    "--text-subtle": "#6b7280",
    "--accent": "#f59e0b",
    "--accent-fg": "#0b0e14",
    "--shadow-card": "none",
    "--radius-card": "0.25rem",
    "--font-body":
      '"IBM Plex Mono", ui-monospace, "SF Mono", Menlo, monospace',
    "--font-mono":
      '"IBM Plex Mono", ui-monospace, "SF Mono", Menlo, monospace',
    "--badge-bg": "#1f2937",
    "--badge-fg": "#fbbf24",
    "--header-eyebrow": "#f59e0b",
    "--code-bg": "#0b0e14",
    "--code-fg": "#fbbf24",
    "--code-border": "#374151",
    "--bubble-user-bg": "#1f2937",
    "--bubble-user-fg": "#fbbf24",
    "--bubble-assistant-bg": "#11151c",
    "--bubble-assistant-fg": "#f59e0b",
    "--thinking-bg": "#1a1f2e",
    "--thinking-border": "#374151",
    "--overlay-bg": "rgba(0, 0, 0, 0.7)",
  },
  colors: {
    chartPalette: ["#f59e0b", "#10b981", "#ef4444", "#3b82f6", "#a855f7", "#eab308", "#06b6d4", "#ec4899"],
    chartDim: "#374151",
    chartAxis: "#6b7280",
    chartGrid: "#1f2937",
    tokenInput: "#3b82f6",
    tokenOutput: "#f59e0b",
    tokenCacheCreation: "#a855f7",
    tokenCacheRead: "#10b981",
    tokenCost: "#ef4444",
    accent: "#f59e0b",
    accentFg: "#0b0e14",
    textPrimary: "#f59e0b",
  },
};

const RAYCAST: Theme = {
  id: "raycast",
  label: "Raycast",
  description: "Warm light, orange accent, soft",
  cssVars: {
    "--bg-app": "#faf7f2",
    "--bg-panel": "#ffffff",
    "--bg-panel-muted": "#f5f0e8",
    "--bg-input": "#f5f0e8",
    "--border": "#ebe3d4",
    "--border-strong": "#d6cab4",
    "--text-primary": "#1a1a1a",
    "--text-secondary": "#404040",
    "--text-muted": "#737373",
    "--text-subtle": "#a3a3a3",
    "--accent": "#ff6363",
    "--accent-fg": "#ffffff",
    "--shadow-card": "0 2px 8px -2px rgba(120, 80, 20, 0.08)",
    "--radius-card": "0.75rem",
    "--font-body":
      '"Inter", ui-sans-serif, system-ui, -apple-system, sans-serif',
    "--font-mono":
      'ui-monospace, "SF Mono", Menlo, monospace',
    "--badge-bg": "#fde8e8",
    "--badge-fg": "#b91c1c",
    "--header-eyebrow": "#ff6363",
    "--code-bg": "#f5f0e8",
    "--code-fg": "#1a1a1a",
    "--code-border": "#d6cab4",
    "--bubble-user-bg": "#fde8e8",
    "--bubble-user-fg": "#1a1a1a",
    "--bubble-assistant-bg": "#ffffff",
    "--bubble-assistant-fg": "#1a1a1a",
    "--thinking-bg": "#fef3e2",
    "--thinking-border": "#f59e0b",
    "--overlay-bg": "rgba(26, 26, 26, 0.4)",
  },
  colors: {
    chartPalette: ["#ff6363", "#f59e0b", "#84cc16", "#06b6d4", "#8b5cf6", "#ec4899", "#14b8a6", "#f97316"],
    chartDim: "#ebe3d4",
    chartAxis: "#a3a3a3",
    chartGrid: "#ebe3d4",
    tokenInput: "#8b5cf6",
    tokenOutput: "#1a1a1a",
    tokenCacheCreation: "#06b6d4",
    tokenCacheRead: "#84cc16",
    tokenCost: "#ff6363",
    accent: "#ff6363",
    accentFg: "#ffffff",
    textPrimary: "#1a1a1a",
  },
};

export const DEFAULT_THEME_ID: ThemeId = "minimal";

export const THEMES: Record<ThemeId, Theme> = {
  minimal: MINIMAL,
  linear: LINEAR,
  vercel: VERCEL,
  neon: NEON,
  warp: WARP,
  mono: MONO,
  terminal: TERMINAL,
  trading: TRADING,
  raycast: RAYCAST,
};

export const THEME_LIST: Theme[] = [
  MINIMAL,
  LINEAR,
  VERCEL,
  NEON,
  WARP,
  MONO,
  TERMINAL,
  TRADING,
  RAYCAST,
];
